### ISSUE TITLE
OAuth login doesn't work on deployment server

### ISSUE THREAD

**Issue by 4U6U57** [Fence-UCSC/Storefront#14]
The OAuth handler redirects login to the hard coded URL `http://localhost:8000/Storefront/default/user/login`, which does not work on the server which expects `https://fence.pythonanywhere.com/Storefront/default/user/login`.

Please change the URL to a generic `/Storefront/default/user/login`

**Comment by tommasobo** [comment]
Not sure if this is possible since the OAuth wants a full link to the actual login page

**Comment by 4U6U57** [comment]
Huh. That is... problematic. Do you mean that the OAuth URL is configured through the third party website (Janrain)?

I guess my question is: where is this page/URL specifically defined?

**Comment by tommasobo** [comment]
https://github.com/Fence-UCSC/Storefront/blob/master/models/db.py#L74

Here

**Comment by 4U6U57** [comment]
I got the URL to change, but Janrain rejects the pythonanywhere domain. I assume that this is something that should be configured on their website? Specific error message below.

> The token URL or xdReceiver has not been whitelisted

**Comment by tommasobo** [comment]
Fixed
